### ISSUE TITLE
Emotiv Insight

### ISSUE THREAD

**Issue by blairzaye** [trentbrooks/BrainWaveOSC#11]
Hey There Trent, 

I am trying to get this going with a Emotiv Insight

I am on a macbook 2020 in win 10 with boot camp and MacOS Catalina with a Emotiv Insight with dongle, trying to get OSC into touchdesigner. most interested in the emotion performance metrics, but would also like the raw data and the brainwaves (alpha, beta, etc)
Tried opening BrainWaveOSC_WIN_0.98 in windows 10 but it comes back with VCOMP120.DLL not found

Also tried on my Mac 2012 with high sierra.. it opens but doesnt detect the Insight.. Any ideas?

**Comment by blairzaye** [comment]
Ah, so i got the BrainWaveOSC_WIN_0.98 in windows 10 by downloading VCOMP120.DLL from https://wikidll.com/microsoft/vcomp120-dll#:~:text=To%20repair%20the%20%E2%80%9Cvcomp120.,within%20the%20Windows%20system%20directory.
but still having the same issue of not seeing the data.. 
I have changed the name in the settings

**Comment by blairzaye** [comment]
Have also tried it with my Muse but I guess they are not connecting because they dont 'use the Thinkgear system' as per your readme.. 

is there anything else I could try?

**Comment by trentbrooks** [comment]
Hey @blairzaye,

Sorry i don't think BrainwaveOSC is compatible with Emotiv insight (although i've never tested). Also the Muse headset has it's own OSC sender which can be run from the command line. I did a EEG workshop a few years ago with a demo (03_muse_osc ) that read the messages into an OF app, as well as a utility script which would launch the Muse OSC script: https://github.com/trentbrooks/EEGWorkshop

Good luck,
Trent
