### ISSUE TITLE
BrainWaveOSC Not Receiving Data

### ISSUE THREAD

**Issue by alimurta** [trentbrooks/BrainWaveOSC#2]
Hey! I have followed all the steps with my MindWave Mobile, but BrainWaveOSC does not detect any data - the left panel remains red. Do you have any idea why this might be happening?

I'm on a Macbook Pro with Yosemite 10. 10. 2.

**Comment by trentbrooks** [comment]
Can you try the older version? See https://github.com/trentbrooks/BrainWaveOSC/issues/1. Someone else was having issues with Mindwave Mobile, this might help.

**Comment by alimurta** [comment]
Thanks for replying. But I tried the full name as well as an older version. Neither worked!

**Comment by alimurta** [comment]
Do I need to find out and change the host and port values by any chance? Because I also couldn't figure those out.

**Comment by alimurta** [comment]
Hey Trent,

Sorry to bother you again! I changed the device value to the full path, as you mentioned in the other thread. Since then it has randomly worked once, also saving CSV data, but hasn't connected since. It's the same read left panel again! Any idea why it might have happened after already working once?

- Ali

**Comment by alimurta** [comment]
Oh and btw the 0.91 was the one that worked that once time.

**Comment by trentbrooks** [comment]
Hey Ali, this sounds more like an osx bluetooth connectivity issue. Email me on trentbrooks at gmail dot com and I will try and help.
